#!/bin/bash
git init -qqq
git remote add origin https://github.com/synventis/magento-docker.git
git fetch origin -qqq
git checkout origin/magento1 -- compose
mv compose/* ./
rm -rf compose .git
git init
