# Mark Shust's Docker Configuration for Magento (https://github.com/markoshust/docker-magento)
# Version 20.1.0

version: "3"

services:
  magento:
    container_name: 'magento'
    image: markoshust/magento-nginx:1.18
    ports:
      - "80:8000"
      - "443:8443"
    volumes: &appvolumes
      - /mnt/magento/appdata:/var/www/html:delegated
      - /mnt/magento/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ~/.composer:/var/www/.composer:delegated
      - sockdata:/sock
    restart: "unless-stopped"

  phpfpm:
    container_name: 'phpfpm'
    image: synventis/magento-php:5.6-fpm
    volumes: *appvolumes
    restart: "unless-stopped"

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:5.6-fpm-6
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

  db:
    container_name: 'sqlserver'
    image: mysql:5.7
    command: --max_allowed_packet=64M --innodb_flush_log_at_trx_commit=2
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - /mnt/magento/dbdata:/var/lib/mysql
    restart: "unless-stopped"

volumes:
  sockdata:
