# Mark Shust's Docker Configuration for Magento (https://github.com/synventis/docker-magento)

version: "3"

services:

  magento:
    container_name: 'magento'
    image: markoshust/magento-nginx:1.18
    ports:
      - "80:8000"
      - "443:8443"
    volumes: &appvolumes
      - /mnt/magento/appdata:/var/www/html
      - /mnt/magento/ssldata:/etc/nginx/certs:ro
      - /mnt/magento/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ~/.composer:/var/www/.composer
      - sockdata:/sock
    restart: "unless-stopped"
    depends_on:
      - phpfpm
      - db

  phpfpm:
    container_name: 'phpfpm'
    image: synventis/magento-php:5.6-fpm
    volumes: *appvolumes
    restart: "unless-stopped"
    depends_on:
      - db

  cron:
    container_name: 'cron'
    image: synventis/magento-php:5.6-fpm
    user: root
    command: /usr/local/bin/cronstart
    tty: true
    volumes: *appvolumes
    restart: "unless-stopped"
    depends_on:
      - db

  db:
    container_name: 'sqlserver'
    image: mysql:5.7
    command: --max_allowed_packet=64M --innodb_flush_log_at_trx_commit=1
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - /mnt/magento/dbdata:/var/lib/mysql
    restart: "unless-stopped"

  logrotate:
    container_name: 'logrotate'
    image: blacklabelops/logrotate
    volumes:
      - /mnt/magento/appdata/var/log:/magento/var/log
    environment:
      - "LOGS_DIRECTORIES=/magento/var/log"
      - "LOGROTATE_COPIES=5"
      - "LOGROTATE_INTERVAL=hourly"
      - "LOGROTATE_SIZE=100M"
      - "LOGROTATE_COMPRESSION=nocompress"
    restart: "unless-stopped"

volumes:
  sockdata:
