# Mark Shust's Docker Configuration for Magento (https://github.com/markoshust/docker-magento)
# Version 20.1.0

version: "3"

services:
  magento:
    container_name: 'magento'
    build: images/nginx
    ports:
      - "80:8000"
      - "443:8443"
    volumes: &appvolumes
      - ./appdata:/var/www/html:delegated
      - ~/.composer:/var/www/.composer:delegated
      - sockdata:/sock
    restart: "unless-stopped"

  phpfpm:
    container_name: 'phpfpm'
    image: markoshust/magento-php:5.6-fpm
    volumes: *appvolumes
    # Linux only: host.docker.internal doesn't exist https://github.com/docker/for-linux/issues/264
    # Uncomment two lines below & replace IP with result of: docker run --rm alpine ip route | awk 'NR==1 {print $3}'
    #extra_hosts:
    #  - "host.docker.internal:IP"
    restart: "unless-stopped"

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:5.6-fpm-6
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

  db:
    container_name: 'sqlserver'
    image: percona:5.7
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql
    restart: "unless-stopped"

volumes:
  dbdata:
  sockdata:
